version: 2
jobs:
  build:
    docker:
      - image: mmontpetit/build_pipeline:latest
    steps:
      - checkout
      - run: ls
  test1:
    docker:
      - image: mmontpetit/build_pipeline:latest
    steps:
      - checkout
      - run: ls
  test2:
    docker:
      - image: mmontpetit/build_pipeline:latest
    steps:
      - checkout
      - run: ls
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - deploy:
          requires:
            - test2
