version: 2.0

jobs:
  build:
    docker:
      - image: mmontpetit/build_pipeline:latest
      - image: mmontpetit/build_pipeline:latest
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: list files
          command: ls

  deploy:
    machine:
        enabled: true
    working_directory: ~/
    steps:
      - run:
          name: Setup Kube
          command: ls -la

      - run:
          command: |
            ls -la
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
